variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/zachariahmiller/packages/uds
  - name: VERSION
    description: The version of the package to build
    # x-release-please-start-version
    default: "1.10.1-uds.1"
    # x-release-please-end
  - name: FLAVOR
    default: "registry1"

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Create the packages
        cmd: |
          set -e
          ZARF_ARCHITECTURE=amd64 uds run -f tasks/create.yaml postgres-operator-package --no-progress --set FLAVOR=${FLAVOR}
          ZARF_ARCHITECTURE=arm64 uds run -f tasks/create.yaml postgres-operator-package --no-progress --set FLAVOR=${FLAVOR}
  
      - description: Publish the packages
        task: publish-package


  - name: publish-package
    description: Publish the packages
    actions:
      - description: Publish the packages
        cmd: |
          set -e
          zarf package publish zarf-package-*-amd64-${VERSION}.tar.zst ${TARGET_REPO}
          if [ ${FLAVOR} != "registry1" ]; then
           zarf package publish zarf-package-*-arm64-${VERSION}.tar.zst ${TARGET_REPO}
          fi
          set +e